version: '3.3'
services:
  server:
    build:
      context: ..
      dockerfile: ./docker/app_dockerfile
    ports:
      - ${PORT}:80
    environment:
      REDIS_URL: redis
      APP_SECRET_KEY: ${APP_SECRET_KEY}
    depends_on:
      - redis

  rq-worker:
    build:
      context: ..
      dockerfile: ./docker/server_dockerfile
    restart: always
    depends_on:
      - redis
    command: python3 ./preload_rq_worker.py redis

  rq-dashboard:
    build:
      context: ..
      dockerfile: ./docker/rq_dashboard_dockerfile
    ports:
      - 9181:9181
    depends_on:
      - redis
    command: rq-dashboard --redis-url redis://redis:6379

  redis:
    image: redis:5
