"""empty message

Revision ID: 35938a6065b3
Revises: 5f7de36f1738
Create Date: 2019-11-19 04:40:56.632860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35938a6065b3'
down_revision = '5f7de36f1738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('install_dt', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_main_fixtures')),
    sa.UniqueConstraint('name', name=op.f('uq_main_fixtures_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_fixtures')
    # ### end Alembic commands ###
