"""empty message

Revision ID: 387d9936b244
Revises: 
Create Date: 2019-11-16 17:07:17.799578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '387d9936b244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_subscribers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('hold', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.CheckConstraint('balance >= 0', name=op.f('ck_main_subscribers_balance_gte_0')),
    sa.CheckConstraint('hold <= balance', name=op.f('ck_main_subscribers_hold_lte_balance')),
    sa.CheckConstraint('hold >= 0', name=op.f('ck_main_subscribers_hold_gte_0')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_main_subscribers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_subscribers')
    # ### end Alembic commands ###
