"""empty message

Revision ID: 5f7de36f1738
Revises: 
Create Date: 2019-11-16 20:42:48.651652

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f7de36f1738'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(text('create EXTENSION if not EXISTS "uuid-ossp";'))

    op.create_table('main_subscribers',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('balance', sa.Numeric(precision=64, scale=2), nullable=False),
    sa.Column('hold', sa.Numeric(precision=64, scale=2), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.CheckConstraint('balance >= 0', name=op.f('ck_main_subscribers_balance_gte_0')),
    sa.CheckConstraint('hold <= balance', name=op.f('ck_main_subscribers_hold_lte_balance')),
    sa.CheckConstraint('hold >= 0', name=op.f('ck_main_subscribers_hold_gte_0')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_main_subscribers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_subscribers')
    # ### end Alembic commands ###
